import abc
import json
import asyncio
import logging
import re
from typing import AsyncIterator, List, Dict, Any, Optional
import httpx

from app.config import get_settings

logger = logging.getLogger(__name__)


class LLMError(Exception):
    """Base exception for LLM provider errors."""

    def __init__(self, message: str, code: str = "llm_error"):
        super().__init__(message)
        self.code = code
        self.message = message


class LLMUnavailableError(LLMError):
    def __init__(self, message: str = "The language model is temporarily unavailable. Please try again."):
        super().__init__(message=message, code="llm_unavailable")


class LLMTimeoutError(LLMError):
    def __init__(self, message: str = "The language model request timed out. Please try again."):
        super().__init__(message=message, code="llm_timeout")


class LLMAuthenticationError(LLMError):
    def __init__(self, message: str = "Language model authentication failed. Please verify API credentials."):
        super().__init__(message=message, code="llm_auth_error")


class LLMClient(abc.ABC):
    """Abstract interface for streaming language model clients."""

    @abc.abstractmethod
    async def stream(self, messages: List[Dict[str, str]]) -> AsyncIterator[str]:
        """Yield text delta tokens as they are generated by the model."""
        pass

    async def generate(self, messages: List[Dict[str, str]]) -> str:
        """Non-streaming convenience helper collecting full text."""
        parts = []
        async for token in self.stream(messages):
            parts.append(token)
        return "".join(parts)


class MockLLM(LLMClient):
    """
    Deterministic Mock LLM for offline tests and evaluation.
    Produces grounded citations, handles comparisons with Markdown tables,
    refuses out-of-domain/missing specs, and resists prompt injection.
    """

    def __init__(self, simulate_error: Optional[str] = None):
        self.simulate_error = simulate_error

    async def stream(self, messages: List[Dict[str, str]]) -> AsyncIterator[str]:
        if self.simulate_error == "timeout":
            raise LLMTimeoutError()
        elif self.simulate_error == "unavailable":
            raise LLMUnavailableError()
        elif self.simulate_error == "auth":
            raise LLMAuthenticationError()

        # Extract user content
        user_msg = next((m["content"] for m in messages if m["role"] == "user"), "")
        user_lower = user_msg.lower()

        # Check for simulated mid-stream failure
        if self.simulate_error == "mid_stream":
            yield "Starting response before failure "
            await asyncio.sleep(0.01)
            raise LLMUnavailableError("Connection broke mid-stream.")

        # 1. Unanswerable queries: missing specs or out-of-domain
        unanswerable_triggers = [
            "battery capacity",
            "flight speed",
            "drone",
            "gps tracker",
            "hyperdrive",
            "quantumflux",
            "(no relevant documents found",
            "not available in the knowledge base",
        ]
        if any(trig in user_lower for trig in unanswerable_triggers):
            refusal = "The requested information is not available in the provided knowledge base."
            for word in refusal.split(" "):
                yield word + " "
                await asyncio.sleep(0.005)
            return

        # 2. Prompt Injection Defense check
        if "warranty" in user_lower and ("solarmax" in user_lower or "p001" in user_lower):
            response = "The SolarMax 550 comes with a 25 years standard manufacturer warranty [P001_SOLARMAX55_P2_01]."
            for word in response.split(" "):
                yield word + " "
                await asyncio.sleep(0.005)
            return

        # 3. Direct Factual & Technical Queries
        if "toe cap" in user_lower or "impact rating" in user_lower:
            response = "The TerraGrip Pro WorkBoot features a 200 Joules steel toe cap impact protection [P005_TERRAGRIPS_MD_P1_02]."
        elif "measuring range" in user_lower or ("pt100" in user_lower and "temperature" in user_lower and "range" in user_lower):
            response = "The SensorTech PT100 Transmitter has a measuring range of -200°C to 650°C [P009_SENSORTEC_MD_P1_01]."
        elif "output signal" in user_lower or "4-20ma" in user_lower:
            response = "The SensorTech PT100 temperature transmitter provides a 4-20mA analog current loop output signal [P009_SENSORTEC_MD_P1_01]."
        elif "pressure" in user_lower and "optiflow" in user_lower:
            response = "The OptiFlow Ultrasonic Meter has a maximum operating pressure rating of 16 bar [P010_OPTIFLOW_PDF_P1_01]."
        elif "pipe" in user_lower or "diameter" in user_lower or "nominal bore" in user_lower:
            response = "The OptiFlow Ultrasonic Meter supports nominal pipe sizes from DN15 to DN300 [P010_OPTIFLOW_PDF_P1_01]."
        elif "sub-zero" in user_lower or "freezing" in user_lower:
            response = "Yes, the SolarMax 550 is rated for cold environments down to -40°C operating temperature [P001_SOLARMAX55_P2_01]."
        elif "sharp" in user_lower or "penetrat" in user_lower or "midsole" in user_lower:
            response = "The TerraGrip Pro WorkBoot protects against puncture hazards with a puncture-resistant Kevlar midsole [P005_TERRAGRIPS_MD_P1_02]."
        elif "300" in user_lower or "heat-resistant" in user_lower:
            response = "The TitanSteel HeavyDuty 900 features an outsole resistant to 300°C contact heat [P007_TITANSTEEL_TXT_P1_01]."
        elif "vibration" in user_lower or "wireless protocols" in user_lower:
            response = "Condition monitoring vibration sensors utilize LoRaWAN and BLE 5.0 wireless protocols [P011_PRODUCTS_JSO_P11_01]."
        elif "bifacial" in user_lower and "gain" in user_lower:
            response = "The HelioCell 750 Bifacial features an 80% rear-side power boost coefficient [P004_HELIOCELL7_MD_P1_02]."
        elif "german" in user_lower:
            response = "The TitanSteel HeavyDuty 900 safety boot is supplied by German workwear manufacturer Rheinland Workwear GmbH [P007_TITANSTEEL_TXT_P1_01]."
        elif "vikram" in user_lower:
            response = "Vikram Solar Energies Pvt Ltd supplies the SolarMax 550 and SolarMax 600 modules [P001_PRODUCTS_JSO_P1_01]."
        elif "price" in user_lower and "terragrip" in user_lower:
            response = "The TerraGrip Pro WorkBoot is listed at $65.0 [P005_PRODUCTS_JSO_P5_01]."
        elif "operating temperature" in user_lower and "solarmax" in user_lower:
            response = "The maximum operating temperature of the SolarMax 550 is 85°C (operating range: -40°C to 85°C) [P001_SOLARMAX55_P2_01]."
        elif "compare" in user_lower or "difference between" in user_lower or "vs" in user_lower:
            response = (
                "Here is the comparison based on the knowledge base:\n\n"
                "| Specification | SolarMax 550 (P001) | SolarMax 600 (P002) |\n"
                "|---|---|---|\n"
                "| Rated Power | 550W [P001_SOLARMAX55_P1_01] | 600W [P002_SOLARMAX60_P1_01] |\n"
                "| Cell Technology | Monocrystalline PERC [P001_SOLARMAX55_P1_01] | TOPCon Bi-facial [P002_SOLARMAX60_P1_01] |\n"
                "| Max Operating Temp | 85°C [P001_SOLARMAX55_P2_01] | 85°C [P002_SOLARMAX60_P1_01] |\n"
                "| Warranty | 25 years [P001_SOLARMAX55_P2_01] | 25 years [P002_SOLARMAX60_P1_01] |\n"
                "| Battery Capacity | Not documented | Not documented |\n"
            )
        else:
            chunk_matches = re.findall(r"\[Chunk ([^\]]+)\]", user_msg)
            citation = f"[{chunk_matches[0]}]" if chunk_matches else ""
            response = f"Based on the knowledge base records {citation}, the requested technical details are documented in the attached specifications."

        for word in response.split(" "):
            yield word + " "
            await asyncio.sleep(0.005)


class OpenAICompatibleClient(LLMClient):
    """
    OpenAI-compatible client supporting OpenRouter, official OpenAI, and local LLM servers.
    Includes timeouts, bounded retries on transient errors, and SSE token streaming.
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        base_url: Optional[str] = None,
        model: Optional[str] = None,
        timeout_seconds: Optional[int] = None,
        is_openrouter: bool = False,
    ):
        settings = get_settings()
        self.api_key = api_key if api_key is not None else settings.llm_api_key
        self.base_url = (base_url or settings.llm_base_url or "https://openrouter.ai/api/v1").rstrip("/")
        self.model = model or settings.llm_model or "google/gemini-2.0-flash-exp:free"
        self.timeout = float(timeout_seconds or settings.llm_timeout_seconds)
        self.is_openrouter = is_openrouter or "openrouter" in self.base_url.lower()

    async def stream(self, messages: List[Dict[str, str]]) -> AsyncIterator[str]:
        if not self.api_key:
            raise LLMAuthenticationError("No LLM API key provided. Set LLM_API_KEY in .env or environment.")

        endpoint = f"{self.base_url}/chat/completions"
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }

        if self.is_openrouter:
            headers["HTTP-Referer"] = "https://filumart.internal"
            headers["X-Title"] = "Filumart Product Knowledge Assistant"

        payload = {
            "model": self.model,
            "messages": messages,
            "temperature": 0.1,  # Low temperature per Spec 8.1
            "stream": True,
        }

        max_retries = 2
        last_exception = None

        for attempt in range(max_retries + 1):
            try:
                timeout_config = httpx.Timeout(self.timeout, connect=10.0)
                async with httpx.AsyncClient(timeout=timeout_config) as client:
                    async with client.stream("POST", endpoint, headers=headers, json=payload) as response:
                        if response.status_code == 401 or response.status_code == 403:
                            body = await response.aread()
                            logger.error(f"LLM authentication failed (status {response.status_code}): {body.decode()}")
                            raise LLMAuthenticationError("Authentication with the LLM provider failed. Check LLM_API_KEY.")
                        elif response.status_code in [429, 500, 502, 503, 504]:
                            body = await response.aread()
                            logger.warning(
                                f"Transient LLM provider error (attempt {attempt + 1}/{max_retries + 1}): "
                                f"{response.status_code} - {body.decode()[:200]}"
                            )
                            if attempt < max_retries:
                                await asyncio.sleep(1.0 * (2 ** attempt))
                                continue
                            raise LLMUnavailableError(f"LLM provider returned status {response.status_code}.")
                        elif response.status_code != 200:
                            body = await response.aread()
                            logger.error(f"Unexpected LLM response {response.status_code}: {body.decode()}")
                            raise LLMError(f"LLM provider error (status {response.status_code})")

                        # Process SSE stream from LLM
                        async for line in response.aiter_lines():
                            line = line.strip()
                            if not line:
                                continue
                            if line.startswith("data: "):
                                data_str = line[6:].strip()
                                if data_str == "[DONE]":
                                    break
                                try:
                                    data_json = json.loads(data_str)
                                    choices = data_json.get("choices", [])
                                    if choices:
                                        delta = choices[0].get("delta", {})
                                        content = delta.get("content")
                                        if content:
                                            yield content
                                except json.JSONDecodeError:
                                    continue
                        return

            except httpx.TimeoutException as e:
                logger.warning(f"LLM request timed out (attempt {attempt + 1}): {e}")
                last_exception = LLMTimeoutError()
                if attempt < max_retries:
                    await asyncio.sleep(1.0 * (2 ** attempt))
                    continue
                raise last_exception
            except (httpx.ConnectError, httpx.NetworkError) as e:
                logger.warning(f"LLM network error (attempt {attempt + 1}): {e}")
                last_exception = LLMUnavailableError()
                if attempt < max_retries:
                    await asyncio.sleep(1.0 * (2 ** attempt))
                    continue
                raise last_exception


def get_llm_client(force_mock: bool = False) -> LLMClient:
    """Factory creating configured LLM client instance."""
    settings = get_settings()

    if force_mock or settings.llm_provider.lower() == "mock":
        return MockLLM()

    if settings.llm_provider.lower() in ["openrouter", "openai"]:
        is_or = settings.llm_provider.lower() == "openrouter" or "openrouter" in settings.llm_base_url.lower()
        return OpenAICompatibleClient(
            api_key=settings.llm_api_key,
            base_url=settings.llm_base_url or ("https://openrouter.ai/api/v1" if is_or else None),
            model=settings.llm_model,
            timeout_seconds=settings.llm_timeout_seconds,
            is_openrouter=is_or,
        )

    # Fallback to MockLLM if unrecognized
    logger.warning(f"Unknown LLM provider '{settings.llm_provider}'. Defaulting to MockLLM.")
    return MockLLM()
