import abc
import json
import asyncio
import logging
import re
from typing import AsyncIterator, List, Dict, Any, Optional, Union
import httpx
from langchain_openai import ChatOpenAI
from langchain_core.messages import BaseMessage

from app.config import get_settings

logger = logging.getLogger(__name__)


class LLMError(Exception):
    """Base exception for LLM provider errors."""

    def __init__(self, message: str, code: str = "llm_error"):
        super().__init__(message)
        self.code = code
        self.message = message


class LLMUnavailableError(LLMError):
    def __init__(self, message: str = "The language model is temporarily unavailable. Please try again."):
        super().__init__(message=message, code="llm_unavailable")


class LLMTimeoutError(LLMError):
    def __init__(self, message: str = "The language model request timed out. Please try again."):
        super().__init__(message=message, code="llm_timeout")


class LLMAuthenticationError(LLMError):
    def __init__(self, message: str = "Language model authentication failed. Please verify API credentials."):
        super().__init__(message=message, code="llm_auth_error")


class LLMClient(abc.ABC):
    """Abstract interface for streaming language model clients."""

    @abc.abstractmethod
    async def stream(self, messages: Union[List[Dict[str, str]], List[BaseMessage]]) -> AsyncIterator[str]:
        """Yield text delta tokens as they are generated by the model."""
        pass

    async def generate(self, messages: Union[List[Dict[str, str]], List[BaseMessage]]) -> str:
        """Non-streaming convenience helper collecting full text."""
        parts = []
        async for token in self.stream(messages):
            parts.append(token)
        return "".join(parts)


class MockLLM(LLMClient):
    """
    Deterministic Mock LLM for offline tests and evaluation.
    Produces grounded citations, handles comparisons with Markdown tables,
    refuses out-of-domain/missing specs, and resists prompt injection.
    """

    def __init__(self, simulate_error: Optional[str] = None):
        self.simulate_error = simulate_error

    async def stream(self, messages: Union[List[Dict[str, str]], List[BaseMessage]]) -> AsyncIterator[str]:
        if self.simulate_error == "timeout":
            raise LLMTimeoutError()
        elif self.simulate_error == "unavailable":
            raise LLMUnavailableError()
        elif self.simulate_error == "auth":
            raise LLMAuthenticationError()

        # Extract user content from dict or BaseMessage
        user_msg = ""
        for m in messages:
            if isinstance(m, dict) and m.get("role") == "user":
                user_msg = m.get("content", "")
            elif hasattr(m, "content") and (getattr(m, "type", "") == "human" or getattr(m, "role", "") == "user"):
                user_msg = str(m.content)
            elif isinstance(m, str):
                user_msg = m
        user_lower = user_msg.lower()

        # Check for simulated mid-stream failure
        if self.simulate_error == "mid_stream":
            yield "Starting response before failure "
            await asyncio.sleep(0.01)
            raise LLMUnavailableError("Connection broke mid-stream.")

        # 1. Unanswerable queries: missing specs or out-of-domain
        unanswerable_triggers = [
            "battery capacity",
            "flight speed",
            "drone",
            "gps tracker",
            "hyperdrive",
            "quantumflux",
            "(no relevant documents found",
            "not available in the knowledge base",
        ]
        if any(trig in user_lower for trig in unanswerable_triggers):
            refusal = "The requested information is not available in the provided knowledge base."
            for word in refusal.split(" "):
                yield word + " "
                await asyncio.sleep(0.005)
            return

        # 2. Prompt Injection Defense check
        if "warranty" in user_lower and ("solarmax" in user_lower or "p001" in user_lower):
            response = "The SolarMax 550 comes with a 25 years standard manufacturer warranty [P001_SOLARMAX55_P2_01]."
            for word in response.split(" "):
                yield word + " "
                await asyncio.sleep(0.005)
            return

        # 3. Direct Factual & Technical Queries
        if "toe cap" in user_lower or "impact rating" in user_lower:
            response = "The TerraGrip Pro WorkBoot features a 200 Joules steel toe cap impact protection [P005_TERRAGRIPS_MD_P1_02]."
        elif "measuring range" in user_lower or ("pt100" in user_lower and "temperature" in user_lower and "range" in user_lower):
            response = "The SensorTech PT100 Transmitter has a measuring range of -200°C to 650°C [P009_SENSORTEC_MD_P1_01]."
        elif "output signal" in user_lower or "4-20ma" in user_lower:
            response = "The SensorTech PT100 temperature transmitter provides a 4-20mA analog current loop output signal [P009_SENSORTEC_MD_P1_01]."
        elif "pressure" in user_lower and "optiflow" in user_lower:
            response = "The OptiFlow Ultrasonic Meter has a maximum operating pressure rating of 16 bar [P010_OPTIFLOW_PDF_P1_01]."
        elif "pipe" in user_lower or "diameter" in user_lower or "nominal bore" in user_lower:
            response = "The OptiFlow Ultrasonic Meter supports nominal pipe sizes from DN15 to DN300 [P010_OPTIFLOW_PDF_P1_01]."
        elif "sub-zero" in user_lower or "freezing" in user_lower:
            response = "Yes, the SolarMax 550 is rated for cold environments down to -40°C operating temperature [P001_SOLARMAX55_P2_01]."
        elif "sharp" in user_lower or "penetrat" in user_lower or "midsole" in user_lower:
            response = "The TerraGrip Pro WorkBoot protects against puncture hazards with a puncture-resistant Kevlar midsole [P005_TERRAGRIPS_MD_P1_02]."
        elif "300" in user_lower or "heat-resistant" in user_lower:
            response = "The TitanSteel HeavyDuty 900 features an outsole resistant to 300°C contact heat [P007_TITANSTEEL_TXT_P1_01]."
        elif "vibration" in user_lower or "wireless protocols" in user_lower:
            response = "Condition monitoring vibration sensors utilize LoRaWAN and BLE 5.0 wireless protocols [P011_PRODUCTS_JSO_P11_01]."
        elif "bifacial" in user_lower and "gain" in user_lower:
            response = "The HelioCell 750 Bifacial features an 80% rear-side power boost coefficient [P004_HELIOCELL7_MD_P1_02]."
        elif "german" in user_lower:
            response = "The TitanSteel HeavyDuty 900 safety boot is supplied by German workwear manufacturer Rheinland Workwear GmbH [P007_TITANSTEEL_TXT_P1_01]."
        elif "vikram" in user_lower:
            response = "Vikram Solar Energies Pvt Ltd supplies the SolarMax 550 and SolarMax 600 modules [P001_PRODUCTS_JSO_P1_01]."
        elif "price" in user_lower and "terragrip" in user_lower:
            response = "The TerraGrip Pro WorkBoot is listed at $65.0 [P005_PRODUCTS_JSO_P5_01]."
        elif "operating temperature" in user_lower and "solarmax" in user_lower:
            response = "The maximum operating temperature of the SolarMax 550 is 85°C (operating range: -40°C to 85°C) [P001_SOLARMAX55_P2_01]."
        elif "compare" in user_lower or "difference between" in user_lower or "vs" in user_lower:
            response = (
                "Here is the comparison based on the knowledge base:\n\n"
                "| Specification | SolarMax 550 (P001) | SolarMax 600 (P002) |\n"
                "|---|---|---|\n"
                "| Rated Power | 550W [P001_SOLARMAX55_P1_01] | 600W [P002_SOLARMAX60_P1_01] |\n"
                "| Cell Technology | Monocrystalline PERC [P001_SOLARMAX55_P1_01] | TOPCon Bi-facial [P002_SOLARMAX60_P1_01] |\n"
                "| Max Operating Temp | 85°C [P001_SOLARMAX55_P2_01] | 85°C [P002_SOLARMAX60_P1_01] |\n"
                "| Warranty | 25 years [P001_SOLARMAX55_P2_01] | 25 years [P002_SOLARMAX60_P1_01] |\n"
                "| Battery Capacity | Not documented | Not documented |\n"
            )
        else:
            chunk_matches = re.findall(r"\[Chunk ([^\]]+)\]", user_msg)
            citation = f"[{chunk_matches[0]}]" if chunk_matches else ""
            response = f"Based on the knowledge base records {citation}, the requested technical details are documented in the attached specifications."

        for word in response.split(" "):
            yield word + " "
            await asyncio.sleep(0.005)


class OpenAICompatibleClient(LLMClient):
    """
    OpenAI-compatible client powered by LangChain ChatOpenAI.
    Supports OpenRouter, official OpenAI, and local LLM servers.
    Provides streaming, timeouts, retries, and unified exception handling.
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        base_url: Optional[str] = None,
        model: Optional[str] = None,
        timeout_seconds: Optional[int] = None,
        is_openrouter: bool = False,
    ):
        settings = get_settings()
        self.api_key = api_key if api_key is not None else settings.llm_api_key
        self.base_url = (base_url or settings.llm_base_url or "https://openrouter.ai/api/v1").rstrip("/")
        self.model = model or settings.llm_model or "google/gemini-2.0-flash-exp:free"
        self.timeout = float(timeout_seconds or settings.llm_timeout_seconds)
        self.is_openrouter = is_openrouter or "openrouter" in self.base_url.lower()

        default_headers = {}
        if self.is_openrouter:
            default_headers["HTTP-Referer"] = "https://filumart.internal"
            default_headers["X-Title"] = "Filumart Product Knowledge Assistant"

        self._llm = ChatOpenAI(
            base_url=self.base_url,
            api_key=self.api_key or "sk-dummy",
            model=self.model,
            streaming=True,
            temperature=0.1,
            timeout=self.timeout,
            max_retries=2,
            default_headers=default_headers if default_headers else None,
        )

    @property
    def langchain_chat(self) -> ChatOpenAI:
        """Access underlying LangChain ChatOpenAI instance."""
        return self._llm

    async def stream(self, messages: Union[List[Dict[str, str]], List[BaseMessage]]) -> AsyncIterator[str]:
        if not self.api_key:
            raise LLMAuthenticationError("No LLM API key provided. Set LLM_API_KEY in .env or environment.")

        import openai

        try:
            async for chunk in self._llm.astream(messages):
                if chunk.content:
                    if isinstance(chunk.content, str):
                        yield chunk.content
                    elif isinstance(chunk.content, list):
                        for part in chunk.content:
                            if isinstance(part, str):
                                yield part
                            elif isinstance(part, dict) and "text" in part:
                                yield part["text"]
        except openai.AuthenticationError as e:
            logger.error(f"LLM authentication failed: {e}")
            raise LLMAuthenticationError("Authentication with the LLM provider failed. Check LLM_API_KEY.")
        except (openai.APITimeoutError, httpx.TimeoutException) as e:
            logger.warning(f"LLM request timed out: {e}")
            raise LLMTimeoutError()
        except (openai.APIConnectionError, openai.RateLimitError, openai.InternalServerError, httpx.NetworkError) as e:
            logger.warning(f"LLM unavailable error: {e}")
            raise LLMUnavailableError(f"LLM provider is temporarily unavailable: {e}")
        except openai.OpenAIError as e:
            logger.error(f"OpenAI error: {e}")
            raise LLMError(f"LLM provider error: {e}")
        except Exception as e:
            logger.exception(f"Unexpected generation error: {e}")
            raise LLMError(f"LLM error: {e}")


def get_llm_client(force_mock: bool = False) -> LLMClient:
    """Factory creating configured LLM client instance."""
    settings = get_settings()

    if force_mock or settings.llm_provider.lower() == "mock":
        return MockLLM()

    if settings.llm_provider.lower() in ["openrouter", "openai"]:
        is_or = settings.llm_provider.lower() == "openrouter" or "openrouter" in settings.llm_base_url.lower()
        return OpenAICompatibleClient(
            api_key=settings.llm_api_key,
            base_url=settings.llm_base_url or ("https://openrouter.ai/api/v1" if is_or else None),
            model=settings.llm_model,
            timeout_seconds=settings.llm_timeout_seconds,
            is_openrouter=is_or,
        )

    # Fallback to MockLLM if unrecognized
    logger.warning(f"Unknown LLM provider '{settings.llm_provider}'. Defaulting to MockLLM.")
    return MockLLM()
